# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 21:33
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GTFSForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('name', models.CharField(blank=True, max_length=50)),
                ('osm_tag', models.CharField(blank=True, max_length=20)),
                ('gtfs_tag', models.CharField(blank=True, max_length=20)),
                ('frequency', models.IntegerField(blank=True, default=3)),
                ('timestamp', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeyValueString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemberRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('n', 'node'), ('w', 'way'), ('r', 'relation')], max_length=1)),
                ('role', models.TextField(blank=True)),
                ('sequence', models.PositiveIntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(null=True)),
                ('uid', models.IntegerField(null=True)),
                ('user', models.TextField(null=True)),
                ('visible', models.BooleanField(default=True)),
                ('version', models.IntegerField(null=True)),
                ('changeset', models.IntegerField(null=True)),
                ('incomplete', models.BooleanField(default=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OSM_Relation',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(null=True)),
                ('uid', models.IntegerField(null=True)),
                ('user', models.TextField(null=True)),
                ('visible', models.BooleanField(default=True)),
                ('version', models.IntegerField(null=True)),
                ('changeset', models.IntegerField(null=True)),
                ('incomplete', models.BooleanField(default=False)),
                ('member_nodes_rel', models.ManyToManyField(through='gtfs.MemberRelation', to='gtfs.Node')),
                ('member_relations_rel', models.ManyToManyField(through='gtfs.MemberRelation', to='gtfs.OSM_Relation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='gtfs.KeyValueString')),
                ('value', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='gtfs.KeyValueString')),
            ],
        ),
        migrations.CreateModel(
            name='Way',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(null=True)),
                ('uid', models.IntegerField(null=True)),
                ('user', models.TextField(null=True)),
                ('visible', models.BooleanField(default=True)),
                ('version', models.IntegerField(null=True)),
                ('changeset', models.IntegerField(null=True)),
                ('incomplete', models.BooleanField(default=False)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.Node')),
                ('way', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.Way')),
            ],
        ),
        migrations.AddField(
            model_name='way',
            name='nodes',
            field=models.ManyToManyField(related_name='nodes_in_way', through='gtfs.WN', to='gtfs.Node'),
        ),
        migrations.AddField(
            model_name='way',
            name='tags',
            field=models.ManyToManyField(blank=True, to='gtfs.Tag'),
        ),
        migrations.AddField(
            model_name='osm_relation',
            name='member_ways_rel',
            field=models.ManyToManyField(through='gtfs.MemberRelation', to='gtfs.Way'),
        ),
        migrations.AddField(
            model_name='osm_relation',
            name='tags',
            field=models.ManyToManyField(blank=True, to='gtfs.Tag'),
        ),
        migrations.AddField(
            model_name='node',
            name='tags',
            field=models.ManyToManyField(blank=True, to='gtfs.Tag'),
        ),
        migrations.AddField(
            model_name='memberrelation',
            name='member_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gtfs.Node'),
        ),
        migrations.AddField(
            model_name='memberrelation',
            name='member_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberrelation_member_relations_rel', to='gtfs.OSM_Relation'),
        ),
        migrations.AddField(
            model_name='memberrelation',
            name='member_way',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gtfs.Way'),
        ),
        migrations.AddField(
            model_name='memberrelation',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.OSM_Relation'),
        ),
        migrations.AlterUniqueTogether(
            name='wn',
            unique_together=set([('node', 'way', 'sequence')]),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set([('key', 'value')]),
        ),
    ]
